### ISSUE TITLE
pascal case "__toString" is converted to sentence case "Tostring" instead of "To string"

### ISSUE THREAD

**Issue by khalyomede** [jawira/case-converter#84] opened 2022-09-03 15:33 UTC
The following reproduction code will show the issue:

```php
use Jawira\CaseConverter\Convert;

require __DIR__ . "/vendor/autoload.php";

$original = "__toString";
$text = new Convert($original);
$expected = "To string";
$sentence = $text->toSentence();

echo $expected === $sentence
    ? "$expected === $sentence" . PHP_EOL
    : "Expected $sentence to be $expected";

echo PHP_EOL;
```

```
Expected Tostring to be To string
```

Is it expected?

FYI here is how one NPM package handles it (as expected in my opinion)

![Capture d’écran du 2022-09-03 18-07-13](https://user-images.githubusercontent.com/15908747/188278943-d07c066a-5733-49a2-9db2-64c4fd5d82dd.png)

**Comment by jawira** [comment] 2024-12-22 00:17
Hi, the reason for this is that the input string "__toString" contains an underscore, therefor the underscore symbol is used to split words, this is described in documentation "Detection algorithm" <https://jawira.github.io/case-converter/detection-algorithm.html>

![Selection_001](https://github.com/user-attachments/assets/fb41a14a-fc59-48d1-90ec-bac427000e4b)

Because you are converting PHP methods, which are written in camel case, a possible solution is to remove underscore character. The output will be **To string**:

```php
<?php
use Jawira\CaseConverter\CaseConverter;

$cc = new CaseConverter();
$method = '__toString';
$method = trim($method,'_');

echo $cc->convert($method)->toSentence(); // To string
```

You can also force input string convention, but the output will keep underscore characters. The output will be **__To string**:

```php
<?php
use Jawira\CaseConverter\CaseConverter;

$cc = new CaseConverter();
$method = '__toString';

echo $cc->convert($method)->fromCamel()->toSentence(); // __To string
```

I will close this issue since this is the expected behavior, feel free to open a new issue if you need further help.

**Closed by jawira** 2024-12-22 00:17 UTC
